### ISSUE TITLE
UUID generator/Identifying Users/Providing and Associating Users with IDs

### ISSUE THREAD

**Issue by robxroy** [angela-andrews/upenn-project1#11]
On page load, a UUID is generated for each user experience (nomination/vote). 

UUID will be pushed to database ref. 

Sample UUID generator: 

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

      <script>
      function guid() {
        function s4() {
          return Math.floor((1 + Math.random()) * 0x10000)
            .toString(16)
            .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
          s4() + '-' + s4() + s4() + s4();
      }
      $(document).ready(function() {
        $('#uuid_p').text(guid());
      })
      </script>

**Comment by CatLibWilk** [comment]
end of day 6/28: user ids are generated on page load, but want to figure out a way to prevent a page reload from same IP address from generating a new id and "user" in the firebase database

**Comment by CatLibWilk** [comment]
closing because we aren't using this functionality anymore
