### ISSUE TITLE
Indicating where user is in the vote process

### ISSUE THREAD

**Issue by CatLibWilk** [angela-andrews/upenn-project1#22]
-on each click, the bg and text color of the card will change to reflect that the card has been selected.  Shade of new color indicates whether card represents 1st, 2nd, 3rd choice

**Comment by CatLibWilk** [comment]
add event listener on .nomination buttons, when one is clicked, runs, checks what vote count is, if first (vc-3) then .addClass to use bootstrap to update bg-color (and text).  continues through each vote for different colors

**Comment by angela-andrews** [comment]
Your code snippet in Slack worked (of course)
